[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --chip nRF52840 --catch-reset --catch-hardfault --allow-erase-all"

[build]
target = "thumbv7em-none-eabihf"

[env]
DEFMT_LOG = "trace"
